import { DeckList, DeckListParser, Card } from './parseDeck';

const metaGrossDeckString = `****** Pokémon Trading Card Game Deck List ******

##Pokémon - 19

* 4 Beldum GRI 83
* 2 Metang GRI 84
* 3 Metagross-GX GRI 85
* 2 Solgaleo-GX SUM 155
* 2 Cosmog SUM 64
* 1 Cosmoem SUM 65
* 3 Tapu Lele-GX GRI 60
* 2 Alolan Vulpix GRI 21

##Trainer Cards - 31

* 3 Professor Sycamore STS 114
* 3 N FCO 105
* 1 Hala GRI 143
* 1 Rescue Stretcher GRI 130
* 1 Skyla BKP 122
* 4 Rare Candy SUM 129
* 1 Heavy Ball BKT 140
* 2 Field Blower GRI 125
* 3 Guzma BUS 115
* 2 Brigette BKT 161
* 2 Choice Band GRI 121
* 4 Ultra Ball FCO 113
* 2 Max Potion GRI 128
* 2 Altar of the Sunne GRI 118

##Energy - 10

* 10 Metal Energy Energy 8

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******`;


describe('Parse Metagross deck', () => {
  let deckList = DeckListParser.parseDeckList(metaGrossDeckString);

  it ('Should have 19 pokemons', () => {
    const numPokemon = deckList.pokemons.reduce(function ( numCards: number, card: Card ) { return numCards + card.numCards; }, 0);
    expect(numPokemon).toEqual(19);
  });

  it ('Should have 31 trainer cards', () => {
    const numTrainers = deckList.trainers.reduce(function ( numCards: number, card: Card ) { return numCards + card.numCards; }, 0);
    expect(numTrainers).toEqual(31);
  });

  it ('Should have 10 energies', () => {
    const numTrainers = deckList.energies.reduce(function ( numCards: number, card: Card ) { return numCards + card.numCards; }, 0);
    expect(numTrainers).toEqual(10);
  });
});
