import { evian } from './evian';

import XXH from 'xxhashjs';
//const XXH = require('xxhashjs'); // Needed to run from VSCode

export class Card {
  numCards: number;
  cardName: string;
  expansion: string;
  collectionNumber: string; // Not a number, e.g. can be SM84
}


export class DeckListParser {
  static stringifyCardArray(cardArray: evian.ICard[]): string {
    return cardArray.reduce( function(a, b) {
      return a.concat(b.numCards.toLocaleString(), b.cardName, b.expansion, ' ');
    }, '');
  }

  static computeDeckListHash(deckList: evian.IDeckList) {
    let s = this.stringifyCardArray(deckList.pokemons);
    s = s.concat(this.stringifyCardArray(deckList.trainers));
    s = s.concat(this.stringifyCardArray(deckList.energies));

    const h = XXH.h32(s, 0xABCD).toString(10);
    return +h;
  }

  static parseCard(cardString: string): Card {
    const card = new Card();
    const cardArray = cardString.split(' ');

    console.assert(cardArray[0] === '*', cardString);

    card.numCards = +cardArray[1];
    card.collectionNumber = cardArray[cardArray.length - 1];
    card.expansion = cardArray[cardArray.length - 2];
    card.cardName = cardArray.slice(2, cardArray.length - 2).join(' ');

    return card;
  }

  static parseDeckList(deckListString: string): evian.IDeckList {
    const deckList =  evian.CreateDeckList();

    const header = '****** Pokémon Trading Card Game Deck List ******';
    const footer = '****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******';

    const deckListArray = deckListString.split('\n');
    console.assert(deckListArray[0] === header);

    let activeArray: evian.ICard[];

    for (const s of deckListArray.slice(1)) {
      if (s === footer) {
        continue;
      }

      switch (s.charAt(0)) {
        case '#': {
          const category = s.split(' ')[0];
          switch (category) {
            case '##Pokémon': {
              activeArray = deckList.pokemons;
              break;
            }
            case '##Trainer': {
              activeArray = deckList.trainers;
              break;
            }
            case '##Energy': {
              activeArray = deckList.energies;
              break;
            }
            default: {
              console.assert(false);
            }
          }
          break;
        }

        case '*': {
          activeArray.push(DeckListParser.parseCard(s));
          break;
        }
        default: {
          //console.log('Ignored: ' + s);
        }
      }
    }

    deckList.pokemons = deckList.pokemons.sort( (a, b) => 0 - (a.cardName < b.cardName ? 1 : -1));
    deckList.id = this.computeDeckListHash(deckList);

    return deckList;
  }
}

export const metaGrossDeckString = `****** Pokémon Trading Card Game Deck List ******

##Pokémon - 19

* 4 Beldum GRI 83
* 2 Metang GRI 84
* 3 Metagross-GX GRI 85
* 2 Solgaleo-GX SUM 155
* 2 Cosmog SUM 64
* 1 Cosmoem SUM 65
* 3 Tapu Lele-GX GRI 60
* 2 Alolan Vulpix GRI 21

##Trainer Cards - 31

* 3 Professor Sycamore STS 114
* 3 N FCO 105
* 1 Hala GRI 143
* 1 Rescue Stretcher GRI 130
* 1 Skyla BKP 122
* 4 Rare Candy SUM 129
* 1 Heavy Ball BKT 140
* 2 Field Blower GRI 125
* 3 Guzma BUS 115
* 2 Brigette BKT 161
* 2 Choice Band GRI 121
* 4 Ultra Ball FCO 113
* 2 Max Potion GRI 128
* 2 Altar of the Sunne GRI 118

##Energy - 10

* 10 Metal Energy Energy 8

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******`;

export const zoroarkGolisopodDeckString = `****** Pokémon Trading Card Game Deck List ******

##Pokémon - 20

* 4 Zorua SLG 52
* 1 Zoroark BKT 91
* 4 Zoroark-GX PR-SM SM84
* 1 Mr. Mime GEN 52
* 3 Wimpod BUS 16
* 2 Golisopod-GX BUS 148
* 1 Tapu Koko PR-SM SM30
* 1 Mewtwo EVO 51
* 3 Tapu Lele-GX GRI 60

##Trainer Cards - 33

* 2 Professor Sycamore STS 114
* 3 Acerola BUS 142
* 4 N FCO 105
* 4 Puzzle of Time BKP 109
* 4 Field Blower GRI 125
* 4 Guzma BUS 115
* 3 Brigette BKT 161
* 1 Mallow GRI 145
* 2 Choice Band GRI 121
* 4 Ultra Ball FCO 113
* 2 Enhanced Hammer GRI 162

##Energy - 7

* 4 Double Colorless Energy NXD 92
* 3 Grass Energy Energy 1

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******`;




//console.log(deckString.split('\n'));
const deckList = DeckListParser.parseDeckList(metaGrossDeckString);
console.log(deckList.id);
deckList.pokemons[0].collectionNumber = 'FOO';
console.log(deckList.id);
deckList.pokemons[0].numCards = 11;
console.log(deckList.id);
